name: Replace

on:
  workflow_dispatch:
  
permissions:
  actions: write
      
jobs:
  Replace:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Replace
      run: |
        ls -lrta
        pw_var=${{ vars.SECRET_NEW }}
        echo $pw_var is variable
        sed -i "s#content#$pw_var#g" secret.txt
        echo --------------------------------------
        cat secret.txt
