name: Replace

on:
  workflow_dispatch:
  
permissions:
  actions: write
      
jobs:
  Replace:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Replace
      run: |
        pw_var=${{ secrets.REPLACE_SECRET }}
        sed -i "s#content#$pw_var#g" ./react-login-page-new/secret.txt
        echo --------------------------------------
        cat ./react-login-page-new/secret.txt
