name: STALE_NOTIFICATION
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5  * * * *'

jobs: 
  StaleNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Creating branch details file
        run:  |
          echo create list
